version: 2
updates:
  - package-ecosystem: npm
    directory: /
    labels:
      - commit::chore
      - type::automated-pr
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    labels:
      - commit::chore
      - type::automated-pr
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
